fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    mysql: https://github.com/puppetlabs/puppetlabs-mysql.git
    sqlite: https://github.com/puppetlabs/puppetlabs-sqlite.git
